language: objective-c
osx_image: xcode9
xcode_project: AppAuth.xcodeproj
xcode_scheme: AppAuth-iOS
before_script:
  - sudo gem install xcpretty
script:
  - xcodebuild -project AppAuth.xcodeproj -scheme "AppAuth-iOS" -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.0' -enableCodeCoverage YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES OTHERCFLAGS="-Werror" test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)

